GET http://localhost:3000/cocktail/type/alco
content-type: application/json


###


GET http://localhost:3000/cocktail/ingredients
content-type: application/json


###

GET http://localhost:3000/cocktail/glasses
content-type: application/json


###


GET http://localhost:3000/cocktail/ingredient/gin

###


GET http://localhost:3000/cocktail/drink/11242
content-type: application/json



###



GET http://localhost:3000/graphql
content-type: application/json
X-REQUEST-TYPE: GraphQL

query($ingredients: String!){
    drinks(ingredients: $ingredients){
        strDrink
        idDrink
        drinkInfo{
            strAlcoholic
            strGlass
            numIngredients
        }
    }
}

{
    "ingredients":"Lemon"
}


###



GET http://localhost:3000/graphql
content-type: application/json
X-REQUEST-TYPE: GraphQL

query($id: String!){
    drink(id: $id){
        strDrink
            idDrink
            strGlass
            strInstructions
            ingredients
            measures
    }
}

{
    "id":"11164"
}

